/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author vivektejwani
 */
public class FeeDetails extends javax.swing.JFrame {

    /**
     * Creates new form FeeDetails
     */
    Connection con;
    Statement stmt,stmt1,stmt2;
    ResultSet rs,rs1,rs2;
    int id;
    double late,total;
    public FeeDetails() {
        initComponents();
    }
    public FeeDetails(int get_id){
        id=get_id;
        initComponents();
        cash_panel.setVisible(false);
        cheque_panel.setVisible(false);
        doConnect();
        
    }
    private void doConnect()
    {
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College?zeroDateTimeBehavior=convertToNull", StartPage.username,StartPage.pass);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stmt1=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stmt2=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql= "select * from student_details where id = "+id;
            rs=stmt.executeQuery(sql);
            rs.next();
            String sql1="select id as 'Payment ID',amount as 'Amount', date_of_pay as 'Date of Payment' from cash_transact where student_id = "+id;
            rs1=stmt1.executeQuery(sql1);
            cash_table.setModel(DbUtils.resultSetToTableModel(rs1));
            String sql2="select id as 'Payment ID',cheque_no as 'Cheque Number',payer_name as 'Payer',bank_name as 'Bank',branch as 'Branch',amount as 'Amount',date_of_pay as 'Date of Payment',date_on_cheque as 'Date on Cheque' from cheque_transact where student_id = "+id;
            rs2=stmt2.executeQuery(sql2);
            cheque_table.setModel(DbUtils.resultSetToTableModel(rs2));
            head_label.setText(rs.getString("stud_name")+"\t"+rs.getString("surname"));
            course_name_label.setText(rs.getString("course_name"));
            join_date_label.setText(rs.getString("joining_date"));
            payable_by_label.setText(rs.getString("date_to_pay_by"));
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date d1,d2;
            d1=df.parse(payable_by_label.getText());
            d2= new Date();
            if(d1.compareTo(d2)>0)
            {
                late=0;
            }
            else if(d1.compareTo(d2)<0)
            {
                late = (d2.getTime() - d1.getTime())/(1000*60*60*24);
            }
            else
            {
        	late =0;
            }
            install_amt_label.setText(Double.toString(rs.getDouble("install_amt")));
            pay_recd_label.setText(Double.toString(rs.getDouble("pay_recd")));
            pay_bal_label.setText(Double.toString(rs.getDouble("pay_bal")));
            late*=StartPage.late_amt;
            late_label.setText(Double.toString(late));
            if(rs.getDouble("pay_bal")<rs.getDouble("install_amt"))
            total=late + Double.parseDouble(pay_bal_label.getText());
            else
            total = late + rs.getDouble("install_amt");
            total_label.setText(Double.toString(total));
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        head_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        join_date_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        payable_by_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        install_amt_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pay_recd_label = new javax.swing.JLabel();
        late_label = new javax.swing.JLabel();
        total_label = new javax.swing.JLabel();
        make_pay_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        course_name_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pay_bal_label = new javax.swing.JLabel();
        cash_details_btn = new javax.swing.JButton();
        cheque_details_btn = new javax.swing.JButton();
        cash_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cash_table = new javax.swing.JTable();
        back_cash = new javax.swing.JButton();
        cheque_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cheque_table = new javax.swing.JTable();
        back_cheque_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        head_label.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        jLabel1.setText("Joining Date :");

        jLabel3.setText("Next Payment Date :");

        jLabel5.setText("Installment Amount:");

        jLabel7.setText("Payment Received :");

        jLabel8.setText("Late Fees :");

        jLabel9.setText("Total Payable :");

        make_pay_btn.setText("Make Payment");
        make_pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_pay_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Course :");

        jLabel4.setText("Payment Balance :");

        cash_details_btn.setText("Cash Payment Details");
        cash_details_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash_details_btnActionPerformed(evt);
            }
        });

        cheque_details_btn.setText("Cheque Payment Details");
        cheque_details_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheque_details_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout main_panelLayout = new org.jdesktop.layout.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panelLayout.createSequentialGroup()
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(main_panelLayout.createSequentialGroup()
                        .add(53, 53, 53)
                        .add(back_btn)
                        .add(128, 128, 128)
                        .add(head_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 280, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(main_panelLayout.createSequentialGroup()
                        .add(68, 68, 68)
                        .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(main_panelLayout.createSequentialGroup()
                                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jLabel3)
                                    .add(jLabel5)
                                    .add(jLabel2))
                                .add(27, 27, 27)
                                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(payable_by_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(install_amt_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(join_date_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .add(course_name_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .add(140, 140, 140)
                                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(jLabel8)
                                    .add(jLabel9)
                                    .add(jLabel4))
                                .add(36, 36, 36)
                                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(total_label)
                                    .add(late_label)
                                    .add(pay_recd_label)
                                    .add(pay_bal_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(main_panelLayout.createSequentialGroup()
                                .add(make_pay_btn)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(cash_details_btn)
                                .add(65, 65, 65)
                                .add(cheque_details_btn)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        main_panelLayout.linkSize(new java.awt.Component[] {install_amt_label, join_date_label, late_label, pay_bal_label, pay_recd_label, payable_by_label, total_label}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panelLayout.createSequentialGroup()
                .add(17, 17, 17)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(head_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(back_btn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 44, Short.MAX_VALUE)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel7)
                        .add(pay_recd_label))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, main_panelLayout.createSequentialGroup()
                        .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(course_name_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .add(9, 9, 9)))
                .add(39, 39, 39)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel4)
                        .add(pay_bal_label))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, join_date_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(48, 48, 48)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel3)
                    .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel8)
                        .add(late_label))
                    .add(payable_by_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(44, 44, 44)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(install_amt_label)
                    .add(jLabel9)
                    .add(total_label))
                .add(39, 39, 39)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(make_pay_btn)
                    .add(cash_details_btn)
                    .add(cheque_details_btn))
                .add(38, 38, 38))
        );

        main_panelLayout.linkSize(new java.awt.Component[] {install_amt_label, payable_by_label}, org.jdesktop.layout.GroupLayout.VERTICAL);

        cash_panel.setBackground(new java.awt.Color(255, 255, 255));

        cash_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Amount", "Date of Payment'"
            }
        ));
        jScrollPane1.setViewportView(cash_table);

        back_cash.setText("Back");
        back_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_cashActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout cash_panelLayout = new org.jdesktop.layout.GroupLayout(cash_panel);
        cash_panel.setLayout(cash_panelLayout);
        cash_panelLayout.setHorizontalGroup(
            cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, cash_panelLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 606, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(78, 78, 78))
            .add(cash_panelLayout.createSequentialGroup()
                .add(59, 59, 59)
                .add(back_cash)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cash_panelLayout.setVerticalGroup(
            cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cash_panelLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(back_cash)
                .add(62, 62, 62)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        cheque_panel.setBackground(new java.awt.Color(255, 255, 255));

        cheque_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Cheque Number", "Payer", "Bank", "Branch", "Amount", "Date of Payment", "Date on Cheque"
            }
        ));
        jScrollPane2.setViewportView(cheque_table);

        back_cheque_btn.setText("Back");
        back_cheque_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_cheque_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout cheque_panelLayout = new org.jdesktop.layout.GroupLayout(cheque_panel);
        cheque_panel.setLayout(cheque_panelLayout);
        cheque_panelLayout.setHorizontalGroup(
            cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cheque_panelLayout.createSequentialGroup()
                .add(36, 36, 36)
                .add(back_cheque_btn)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, cheque_panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
        );
        cheque_panelLayout.setVerticalGroup(
            cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, cheque_panelLayout.createSequentialGroup()
                .add(25, 25, 25)
                .add(back_cheque_btn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 64, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(108, 108, 108))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(cash_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(cheque_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(cash_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(cheque_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new OldStudent().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void make_pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_pay_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            this.dispose();
            new pay_now(rs.getString("stud_name"),rs.getString("surname")).setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", 1);
        }
    }//GEN-LAST:event_make_pay_btnActionPerformed

    private void cash_details_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_details_btnActionPerformed
        // TODO add your handling code here:
        main_panel.setVisible(false);
        cash_panel.setVisible(true);
    }//GEN-LAST:event_cash_details_btnActionPerformed

    private void cheque_details_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheque_details_btnActionPerformed
        // TODO add your handling code here:
        main_panel.setVisible(false);
        cheque_panel.setVisible(true);
    }//GEN-LAST:event_cheque_details_btnActionPerformed

    private void back_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_cashActionPerformed
        // TODO add your handling code here:
        cash_panel.setVisible(false);
        main_panel.setVisible(true);
    }//GEN-LAST:event_back_cashActionPerformed

    private void back_cheque_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_cheque_btnActionPerformed
        // TODO add your handling code here:
        cheque_panel.setVisible(false);
        main_panel.setVisible(true);
    }//GEN-LAST:event_back_cheque_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeeDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton back_cash;
    private javax.swing.JButton back_cheque_btn;
    private javax.swing.JButton cash_details_btn;
    private javax.swing.JPanel cash_panel;
    private javax.swing.JTable cash_table;
    private javax.swing.JButton cheque_details_btn;
    private javax.swing.JPanel cheque_panel;
    private javax.swing.JTable cheque_table;
    private javax.swing.JLabel course_name_label;
    private javax.swing.JLabel head_label;
    private javax.swing.JLabel install_amt_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel join_date_label;
    private javax.swing.JLabel late_label;
    private javax.swing.JPanel main_panel;
    private javax.swing.JButton make_pay_btn;
    private javax.swing.JLabel pay_bal_label;
    private javax.swing.JLabel pay_recd_label;
    private javax.swing.JLabel payable_by_label;
    private javax.swing.JLabel total_label;
    // End of variables declaration//GEN-END:variables
}
