/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;

/**
 *
 * @author vivektejwani
 */
public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form NewStudent
     */
    Connection con;
    Statement stmt,stmt1;
    ResultSet rs,rs1;
    double total;
    String stud_name,surname;
    public NewStudent() {
        initComponents();
        jPanel2.setVisible(false);
        doConnect();
    }
    public void doConnect()
    {
        try
        {   
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College?zeroDateTimeBehavior=convertToNull", "root", null);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql1="select course_name from courses";
            rs1=stmt.executeQuery(sql1);
            while(rs1.next()) 
            {
                course_box.addItem(rs1.getString("course_name"));
            }
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        new_stud_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        father_label = new javax.swing.JLabel();
        mother_label = new javax.swing.JLabel();
        dob_label = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        surname_text = new javax.swing.JTextField();
        father_text = new javax.swing.JTextField();
        mother_text = new javax.swing.JTextField();
        dob_choose = new com.toedter.calendar.JDateChooser();
        address_label = new javax.swing.JLabel();
        address_text = new javax.swing.JTextField();
        contact_label = new javax.swing.JLabel();
        contact_text = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        school_label = new javax.swing.JLabel();
        school_text = new javax.swing.JTextField();
        board_box = new javax.swing.JComboBox();
        board_label = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        surname_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        parent_contact_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        email_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        parent_email_text = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        new_stud_label1 = new javax.swing.JLabel();
        course_label = new javax.swing.JLabel();
        course_box = new javax.swing.JComboBox();
        percent_label = new javax.swing.JLabel();
        percent_text = new javax.swing.JTextField();
        percent_sign_label = new javax.swing.JLabel();
        occupation1_label = new javax.swing.JLabel();
        occupation1_text = new javax.swing.JTextField();
        occupation2_label = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        clear2_btn = new javax.swing.JButton();
        occupation3_label = new javax.swing.JLabel();
        occupation4_label = new javax.swing.JLabel();
        occupation2_text = new javax.swing.JTextField();
        fees1_label = new javax.swing.JLabel();
        edu_cess_label1 = new javax.swing.JLabel();
        other_label1 = new javax.swing.JLabel();
        total_label1 = new javax.swing.JLabel();
        fees_label2 = new javax.swing.JLabel();
        edu_cess_label2 = new javax.swing.JLabel();
        other_label2 = new javax.swing.JLabel();
        total_label2 = new javax.swing.JLabel();
        pay_now_btn = new javax.swing.JButton();
        pay_ltr_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reg_no_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pay_type_box = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        new_stud_label.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        new_stud_label.setText("Create a new student");

        name_label.setText("Name :");

        father_label.setText("Father's name :");

        mother_label.setText("Mother's name :");

        dob_label.setText("Date of Birth :");

        name_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name_textKeyPressed(evt);
            }
        });

        surname_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname_textActionPerformed(evt);
            }
        });

        mother_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mother_textActionPerformed(evt);
            }
        });

        dob_choose.setDateFormatString("yyyy-MM-dd");

        address_label.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        address_label.setText("Address :");

        address_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_textActionPerformed(evt);
            }
        });

        contact_label.setText("Contact No :");

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        school_label.setText("School :");

        board_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S.S.C", "I.C.S.E", "C.B.S.E", "Other" }));

        board_label.setText("Board :");

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        next_btn.setText("Next");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });

        surname_label.setText("Surname :");

        jLabel1.setText("Contact No :");

        jLabel2.setText("E-mail ID :");

        jLabel3.setText("Parent's Email :");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(back_btn)
                            .add(118, 118, 118)
                            .add(new_stud_label))
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(name_label)
                            .add(73, 73, 73)
                            .add(name_text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(address_label)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(father_label)
                            .add(surname_label))
                        .add(22, 22, 22)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(father_text)
                            .add(surname_text)
                            .add(email_text)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mother_label)
                            .add(dob_label))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(mother_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(115, 115, 115)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(contact_label)
                                    .add(school_label)
                                    .add(board_label)
                                    .add(jLabel3)))
                            .add(dob_choose, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED, 17, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(clear_btn)
                        .add(18, 18, 18)
                        .add(next_btn)
                        .add(17, 17, 17))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(parent_email_text)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, contact_text)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, address_text)
                            .add(parent_contact_text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .add(school_text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, board_box, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(56, 56, 56))))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {father_text, mother_text, name_text}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(new_stud_label)
                            .add(back_btn))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(2, 2, 2)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(name_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(name_label)))
                            .add(address_label))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(surname_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(surname_label))
                            .add(contact_label))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(father_label)
                            .add(father_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(email_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3)
                            .add(parent_email_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(23, 23, 23)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(mother_label)
                            .add(mother_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(school_label))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(24, 24, 24)
                                .add(dob_label))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(board_label)
                                    .add(dob_choose, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(66, 66, 66)
                        .add(address_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(contact_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(parent_contact_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(63, 63, 63)
                        .add(school_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(board_box, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(clear_btn)
                            .add(next_btn))))
                .add(18, 46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        new_stud_label1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        new_stud_label1.setText("Create a new student");

        course_label.setText("Course :");

        course_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose" }));
        course_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_boxActionPerformed(evt);
            }
        });

        percent_label.setText("Percentage :");

        percent_sign_label.setText("%");

        occupation1_label.setText("Father's ");

        occupation1_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupation1_textActionPerformed(evt);
            }
        });

        occupation2_label.setText("Occupation :");

        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        clear2_btn.setText("Clear");
        clear2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2_btnActionPerformed(evt);
            }
        });

        occupation3_label.setText("Mother's");

        occupation4_label.setText("Occupation :");

        fees1_label.setText("Fees :");

        edu_cess_label1.setText("Educational Cess :");

        other_label1.setText("Other Tax :");

        total_label1.setText("Grand Total :");

        fees_label2.setText("Rs.");

        edu_cess_label2.setText("Rs.");

        other_label2.setText("Rs.");

        total_label2.setText("Rs.");

        pay_now_btn.setText("Pay Now");
        pay_now_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_now_btnActionPerformed(evt);
            }
        });

        pay_ltr_btn.setText("Pay Later");
        pay_ltr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_ltr_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Registration");

        jLabel5.setText("Number :");

        jLabel6.setText("Type of ");

        jLabel7.setText("Payment :");

        pay_type_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose", "Monthly", "Quarterly", "Half-yearly", "Annually" }));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(265, 265, 265)
                .add(new_stud_label1)
                .addContainerGap(270, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(course_label)
                    .add(percent_label)
                    .add(occupation1_label)
                    .add(occupation2_label)
                    .add(occupation3_label)
                    .add(occupation4_label)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel7)
                    .add(jLabel6))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(course_box, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(percent_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(percent_sign_label))
                    .add(reg_no_text)
                    .add(occupation2_text)
                    .add(occupation1_text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .add(pay_type_box, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(98, 98, 98)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(edu_cess_label1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(edu_cess_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(fees1_label)
                            .add(total_label1)
                            .add(other_label1))
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(78, 78, 78)
                                .add(fees_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, other_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, total_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(clear2_btn)
                            .add(pay_ltr_btn))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pay_now_btn)
                            .add(save_btn))
                        .add(58, 58, 58)))
                .add(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(new_stud_label1)
                .add(51, 51, 51)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(fees_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(course_label)
                        .add(course_box, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(fees1_label)))
                .add(21, 21, 21)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(percent_label)
                    .add(percent_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(percent_sign_label)
                    .add(edu_cess_label1)
                    .add(edu_cess_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(occupation1_label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(occupation2_label))
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(occupation1_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(other_label1)
                        .add(other_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(occupation3_label)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(occupation4_label))
                            .add(occupation2_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(total_label1)
                            .add(total_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(save_btn)
                            .add(clear2_btn))))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(2, 2, 2)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(pay_now_btn)
                            .add(pay_ltr_btn)
                            .add(jLabel5)))
                    .add(reg_no_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel7))
                    .add(pay_type_box, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
        // TODO add your handling code here:
        
        {
            
            jPanel1.setVisible(false);
            jPanel2.setVisible(true);
            pay_now_btn.setEnabled(false);
            pay_ltr_btn.setEnabled(false);
        }
        

    }//GEN-LAST:event_next_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:

        new NewStudent().setVisible(true);
        dispose();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        new StartPage().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void address_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_textActionPerformed

    private void mother_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mother_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mother_textActionPerformed

    private void occupation1_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupation1_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupation1_textActionPerformed

    private void clear2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2_btnActionPerformed
        // TODO add your handling code here:
        new NewStudent().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_clear2_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College?zeroDateTimeBehavior=convertToNull", StartPage.username,StartPage.pass);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stmt1=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql="select * from student_details";
            String sql1="select * from courses where course_name = '"+(String)course_box.getSelectedItem()+"'";
            rs=stmt.executeQuery(sql);
            rs1=stmt1.executeQuery(sql1);
            rs1.next();
            while(rs.next())
            {}
            int dur=rs1.getInt("duration");
            double installment=0.0d;
            rs.moveToInsertRow();
            rs.updateString("stud_name",name_text.getText());
            rs.updateString("surname", surname_text.getText());
            rs.updateString("father_name", father_text.getText());
            rs.updateString("mother_name", mother_text.getText());
            rs.updateString("address", address_text.getText());
            rs.updateString("school", school_text.getText());
            rs.updateString("board", (String)board_box.getSelectedItem());
            rs.updateLong("contact_no", Long.parseLong(contact_text.getText()));
            rs.updateLong("parent_contact", Long.parseLong(parent_contact_text.getText()));
            rs.updateString("stud_email", email_text.getText());
            rs.updateString("parent_email", parent_email_text.getText());
            java.text.DateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd");
            java.util.Date d=dob_choose.getDate();
            String reportDate = df.format(d);
            rs.updateString("dob",reportDate);
            rs.updateInt("roll_no", 0000);
            rs.updateString("course_name", rs1.getString("course_name"));
            java.util.Date d1= new Date();
            String reportDate1 = df.format(d1);
            rs.updateString("joining_date", reportDate1);
            rs.updateString("father_occupation", occupation1_text.getText());
            rs.updateString("mother_occupation", occupation2_text.getText());
            rs.updateLong("reg_no", Long.parseLong(reg_no_text.getText()));
            rs.updateDouble("fees",total);
            
            java.util.Calendar c = java.util.Calendar.getInstance(); 
            c.setTime(d1); 
            rs.updateInt("percentage", Integer.parseInt(percent_text.getText()));
            String temp = (String)pay_type_box.getSelectedItem();
            if(temp.equalsIgnoreCase("monthly"))
            {
                rs.updateInt("type_of_pay", 1);
                c.add(java.util.Calendar.MONTH, 1);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
                installment=total/dur;
                rs.updateDouble("install_amt",installment);
            }
            else if(temp.equalsIgnoreCase("quarterly"))
            {
                rs.updateInt("type_of_pay", 2);
                c.add(java.util.Calendar.MONTH, 3);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
                installment=total*3/dur;
                rs.updateDouble("install_amt",installment);
            }
            else if(temp.equalsIgnoreCase("half-yearly"))
            {
                rs.updateInt("type_of_pay", 3);
                c.add(java.util.Calendar.MONTH, 6);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
                installment=total*6/dur;
                rs.updateDouble("install_amt",installment);
            }
            else if(temp.equalsIgnoreCase("annually"))
            {
                rs.updateInt("type_of_pay", 4);
                c.add(java.util.Calendar.MONTH, 12);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
                installment=total*12/dur;
                rs.updateDouble("install_amt",installment);
            }
            rs.updateDouble("pay_recd", 0);
            rs.updateInt("no_of_pays_made", 0);
            rs.updateDouble("pay_bal",total);
            rs.insertRow();
            stmt.close();
            rs.close();
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            sql="Select * from student_details";
            rs=stmt.executeQuery(sql);
            rs.next();
            JOptionPane.showMessageDialog(null,"Saved!",null,1);
            pay_now_btn.setEnabled(true);
            pay_ltr_btn.setEnabled(true);
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error", 1);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", 1);
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void course_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_boxActionPerformed
        // TODO add your handling code here:
        try
        {
            
            String sql1="select * from courses where course_name = '"+(String)course_box.getSelectedItem()+"'";
            rs1=stmt.executeQuery(sql1);
            rs1.next();
            fees_label2.setText("Rs. "+Double.toString(rs1.getDouble("fees")));
            double fee = rs1.getDouble("fees");
            double edu=rs1.getDouble("education_cess");
            edu_cess_label2.setText("Rs. "+Double.toString(edu));
            double other =rs1.getDouble("other_tax");
            other_label2.setText("Rs. "+Double.toString(other));
            total = fee+edu+other;
            total_label2.setText("Rs. "+Double.toString(total));
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null,err.getMessage(),"Error", 1);
        }
    }//GEN-LAST:event_course_boxActionPerformed

    private void surname_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname_textActionPerformed

    private void name_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_textKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textKeyPressed

    private void pay_now_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_now_btnActionPerformed
        try {
            // TODO add your handling code here:
            rs.close();
            rs1.close();
            stud_name=name_text.getText();
            surname=surname_text.getText();
            new pay_now(stud_name,surname).setVisible(true);
            dispose();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error!", 1);
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);

        }
        
    }//GEN-LAST:event_pay_now_btnActionPerformed

    private void pay_ltr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_ltr_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new StartPage().setVisible(true);
    }//GEN-LAST:event_pay_ltr_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField address_text;
    private javax.swing.JButton back_btn;
    private javax.swing.JComboBox board_box;
    private javax.swing.JLabel board_label;
    private javax.swing.JButton clear2_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel contact_label;
    private javax.swing.JTextField contact_text;
    private javax.swing.JComboBox course_box;
    private javax.swing.JLabel course_label;
    private com.toedter.calendar.JDateChooser dob_choose;
    private javax.swing.JLabel dob_label;
    private javax.swing.JLabel edu_cess_label1;
    private javax.swing.JLabel edu_cess_label2;
    private javax.swing.JTextField email_text;
    private javax.swing.JLabel father_label;
    private javax.swing.JTextField father_text;
    private javax.swing.JLabel fees1_label;
    private javax.swing.JLabel fees_label2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mother_label;
    private javax.swing.JTextField mother_text;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel new_stud_label;
    private javax.swing.JLabel new_stud_label1;
    private javax.swing.JButton next_btn;
    private javax.swing.JLabel occupation1_label;
    private javax.swing.JTextField occupation1_text;
    private javax.swing.JLabel occupation2_label;
    private javax.swing.JTextField occupation2_text;
    private javax.swing.JLabel occupation3_label;
    private javax.swing.JLabel occupation4_label;
    private javax.swing.JLabel other_label1;
    private javax.swing.JLabel other_label2;
    private javax.swing.JTextField parent_contact_text;
    private javax.swing.JTextField parent_email_text;
    private javax.swing.JButton pay_ltr_btn;
    private javax.swing.JButton pay_now_btn;
    private javax.swing.JComboBox pay_type_box;
    private javax.swing.JLabel percent_label;
    private javax.swing.JLabel percent_sign_label;
    private javax.swing.JTextField percent_text;
    private javax.swing.JPopupMenu pm;
    private javax.swing.JTextField reg_no_text;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel school_label;
    private javax.swing.JTextField school_text;
    private javax.swing.JLabel surname_label;
    private javax.swing.JTextField surname_text;
    private javax.swing.JLabel total_label1;
    private javax.swing.JLabel total_label2;
    // End of variables declaration//GEN-END:variables
}
