
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vivektejwani
 */
public class OldStudent extends javax.swing.JFrame {

    /**
     * Creates new form OldStudent
     */
    Connection con;
    Statement stmt;
    ResultSet rs;
    int id;
    String name=null;
    String father=null;
    String mother=null;
    String surname = null;
    public OldStudent() {
        initComponents();
        jPanel2.setVisible(false);
        doConnect();
        select_btn.setEnabled(false);
        
    }
    public void doConnect()
    {
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College?zeroDateTimeBehavior=convertToNull", StartPage.username,StartPage.pass);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null,err.getMessage(),"Error",1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        name_label2 = new javax.swing.JLabel();
        surname_label2 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        see_btn = new javax.swing.JButton();
        pay_now_btn = new javax.swing.JButton();
        delete_student_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        items_pane = new javax.swing.JScrollPane();
        items_table = new javax.swing.JTable();
        name_label = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        father_label = new javax.swing.JLabel();
        father_text = new javax.swing.JTextField();
        mother_label = new javax.swing.JLabel();
        mother_text = new javax.swing.JTextField();
        find_btn = new javax.swing.JButton();
        select_btn = new javax.swing.JButton();
        surname_label = new javax.swing.JLabel();
        surname_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        name_label2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        surname_label2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        update_btn.setText("Update Details");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        see_btn.setText("See Payment Details");
        see_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see_btnActionPerformed(evt);
            }
        });

        pay_now_btn.setText("Make Payment");
        pay_now_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_now_btnActionPerformed(evt);
            }
        });

        delete_student_btn.setText("Delete");
        delete_student_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_student_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(153, 153, 153)
                .add(update_btn)
                .add(71, 71, 71)
                .add(pay_now_btn)
                .add(60, 60, 60)
                .add(see_btn)
                .addContainerGap(90, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(name_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(73, 73, 73)
                .add(surname_label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(179, 179, 179))
            .add(jPanel2Layout.createSequentialGroup()
                .add(65, 65, 65)
                .add(back_btn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(delete_student_btn)
                .add(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(37, 37, 37)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(back_btn)
                    .add(delete_student_btn))
                .add(38, 38, 38)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(surname_label2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .add(name_label2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 147, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(update_btn)
                    .add(pay_now_btn)
                    .add(see_btn))
                .add(74, 74, 74))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Select Student :");

        items_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Roll Number", "Father's Name", "Mother's Name"
            }
        ));
        items_table.setEnabled(false);
        items_table.setShowGrid(true);
        items_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                items_tableMouseClicked(evt);
            }
        });
        items_pane.setViewportView(items_table);

        name_label.setText("Name :");

        father_label.setText("Father's Name");

        mother_label.setText("Mother's Name :");

        find_btn.setText("Find");
        find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_btnActionPerformed(evt);
            }
        });

        select_btn.setText("Select");
        select_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_btnActionPerformed(evt);
            }
        });

        surname_label.setText("Surname :");

        surname_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname_textActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(276, 276, 276)
                        .add(find_btn)
                        .add(111, 111, 111)
                        .add(select_btn))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(322, 322, 322)
                        .add(jLabel1)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(items_pane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(name_label)
                            .add(father_label))
                        .add(38, 38, 38)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(father_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(name_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mother_label)
                            .add(surname_label))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(mother_text)
                            .add(surname_text))))
                .add(82, 82, 82))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {father_text, mother_text, name_text}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(items_pane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(name_label)
                    .add(name_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(surname_label)
                    .add(surname_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(father_label)
                    .add(father_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(mother_label)
                    .add(mother_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 51, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(find_btn)
                    .add(select_btn))
                .add(46, 46, 46))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            name = name_text.getText();
            father = father_text.getText();
            mother = mother_text.getText();
            surname=surname_text.getText();
            String sql = null;
             if(!"".equals(name) && !"".equals(father) && !"".equals(mother) && !"".equals(surname))
            {
                 sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where stud_name = '"+name+"' and father_name = '"+father+"' and mother_name = '"+mother+"' and surname = '"+surname+"'";
            }
            else
            {
            if(!"".equals(name) && !"".equals(father)&&!"".equals(surname))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where stud_name = '"+name+"' and father_name = '"+father+"' and surname = '"+surname+"'";
            }
            else if(!"".equals(name) && !"".equals(mother)&&!"".equals(surname))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where stud_name = '"+name+"' and mother_name = '"+mother+"' and surname = '"+surname+"'";
            }
            else if(!"".equals(father) && !"".equals(mother)&&!"".equals(surname))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where father_name = '"+father+"' and mother_name = '"+mother+"' and surname = '"+surname+"'";
            }
            else if(!"".equals(name) && !"".equals(father)&& !"".equals(mother))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where stud_name = '"+name+"' and father_name = '"+father+"' and mother_name = '"+mother+"'";
            }
            else if(!"".equals(name) && !"".equals(father))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where stud_name = '"+name+"' and father_name = '"+father+"'";
            }
            else if(!"".equals(name) && !"".equals(mother))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where stud_name = '"+name+"' and mother_name = '"+mother+"'";
            }
            else if(!"".equals(father) && !"".equals(mother))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where father_name = '"+father+"' and mother_name = '"+mother+"'";
            }
            else if(!"".equals(name) && !"".equals(surname))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where stud_name = '"+name+"' and surname = '"+surname+"'";
            }
            
            else if(!"".equals(name))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where stud_name = '"+name+"'";
            }
            else if(!"".equals(father))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where father_name = '"+father+"'";
            }
            else if(!"".equals(mother))
            {
                sql = "select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where mother_name = '"+mother+"'";
            }
            else if(!"".equals(surname))
            {
                sql="select id as 'ID',stud_name as 'Name',surname as 'Surname',reg_no as 'Reg. No.',father_name as 'Fathers Name', mother_name as 'Mothers Name' from student_details where surname = '"+surname+"'";
            }
            else
            {
                JOptionPane.showMessageDialog(null,"No Data Entered","Error",1);
            }
            }
        rs=stmt.executeQuery(sql);
        items_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null,err.getMessage(),"Error",1);
        }
    }//GEN-LAST:event_find_btnActionPerformed

    private void items_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_items_tableMouseClicked
        // TODO add your handling code here:
        int row = items_table.rowAtPoint(evt.getPoint());
        items_table.setRowSelectionInterval(row, row);
        name = (String)items_table.getModel().getValueAt(row, 1);
        id = (Integer)items_table.getModel().getValueAt(row, 0);
        select_btn.setEnabled(true);
    }//GEN-LAST:event_items_tableMouseClicked

    private void select_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_btnActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "You've selected :\n"+name+" \nID :"+Integer.toString(id),null , 1);
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        try{
            String sql = "select * from student_details where id = "+id;
            rs=stmt.executeQuery(sql);
            rs.next();
            name_label2.setText(rs.getString("stud_name"));
            surname_label2.setText(rs.getString("surname"));
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(),"Error!",1);
        }
    }//GEN-LAST:event_select_btnActionPerformed

    private void surname_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname_textActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        new UpdateDetails(id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update_btnActionPerformed

    private void pay_now_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_now_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            name=rs.getString("stud_name");
            surname=rs.getString("surname");
            rs.close();
            new pay_now(name,surname).setVisible(true);
            this.dispose();
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", 1);
        }
        
    }//GEN-LAST:event_pay_now_btnActionPerformed

    private void see_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FeeDetails(id).setVisible(true);
    }//GEN-LAST:event_see_btnActionPerformed

    private void delete_student_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_student_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            if(JOptionPane.showConfirmDialog(null, "Delete "+name_label2.getText()+" ?", "Confirmation", JOptionPane.OK_CANCEL_OPTION) == 0)
            {
                rs.deleteRow();
                this.dispose();
                new OldStudent().setVisible(true);
            }
            
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
    }//GEN-LAST:event_delete_student_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OldStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OldStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OldStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OldStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OldStudent().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton delete_student_btn;
    private javax.swing.JLabel father_label;
    private javax.swing.JTextField father_text;
    private javax.swing.JButton find_btn;
    private javax.swing.JScrollPane items_pane;
    private javax.swing.JTable items_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mother_label;
    private javax.swing.JTextField mother_text;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel name_label2;
    private javax.swing.JTextField name_text;
    private javax.swing.JButton pay_now_btn;
    private javax.swing.JButton see_btn;
    private javax.swing.JButton select_btn;
    private javax.swing.JLabel surname_label;
    private javax.swing.JLabel surname_label2;
    private javax.swing.JTextField surname_text;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
    
