/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
/**
 *
 * @author vivektejwani
 */
public class pay_now extends javax.swing.JFrame {

    /**
     * Creates new form pay_now
     */
    Connection con;
    Statement stmt,stmt1;
    ResultSet rs,rs1;
    String stud_name, surname;
    double late,d;
    String sql, s;
    Date d1,d2;
    
    
    public pay_now(){
       
        initComponents();
    }
    public pay_now(String s,String s1) throws ParseException
    {
        stud_name=s;
        surname=s1;
        initComponents();
        main_panel.setVisible(true);
        cash_panel.setVisible(false);
        cheque_panel.setVisible(false);
        doConnect();
    }
    private void doConnect() throws ParseException
    {   
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College?zeroDateTimeBehavior=convertToNull", StartPage.username,StartPage.pass);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stmt1=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            this.sql = "Select * from student_details where stud_name = '"+stud_name+"' and surname ='"+surname+"'";
            rs=stmt.executeQuery(sql);
            rs.next();
            name_label.setText(rs.getString("stud_name"));
            name_cash_label.setText(rs.getString("stud_name"));
            surname_label.setText(rs.getString("surname"));
            surname_cash_label.setText(rs.getString("surname"));
            amt_paid_label.setText(Double.toString(rs.getDouble("pay_recd")));
            pay_recd_label.setText(Double.toString(rs.getDouble("pay_recd")));
            this.d = rs.getDouble("pay_bal");
            installment_cash_label.setText(Double.toString(rs.getDouble("install_amt")));
            double install=rs.getDouble("install_amt");
            this.s=rs.getString("date_to_pay_by");
            java.text.DateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd");
            this.d1 = df.parse(s);
            this.d2= new Date();
            if(d1.compareTo(d2)>0)
            {
        	this.late = 0;
            }
            else if(d1.compareTo(d2)<0)
            {
                this.late = (d2.getTime() - d1.getTime())/(1000*60*60*24);
                this.late *=StartPage.late_amt;
            }
            else if(d1.compareTo(d2)==0)
            {
        	this.late = 0;
            }
            late_fees_cash_label.setText(Double.toString(late));
            payable_label.setText(this.s);
            due_date_cash_label.setText(this.s);
            this.d+=this.late;
            install+=late;
            amt_bal_label.setText(Double.toString(this.d));
            if(d>=install)
                total_payable_cash_label.setText(Double.toString(install));
            else
                total_payable_cash_label.setText(Double.toString(d));
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cash_btn = new javax.swing.JButton();
        name_label = new javax.swing.JLabel();
        surname_label = new javax.swing.JLabel();
        amt_paid_label = new javax.swing.JLabel();
        amt_bal_label = new javax.swing.JLabel();
        payable_label = new javax.swing.JLabel();
        cash_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name_cash_label = new javax.swing.JLabel();
        surname_cash_label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pay_recd_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        installment_cash_label = new javax.swing.JLabel();
        due_date_cash_label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        late_fees_cash_label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        total_payable_cash_label = new javax.swing.JLabel();
        cancel_cash_btn = new javax.swing.JButton();
        payment_cash_label = new javax.swing.JLabel();
        pay_cash_text = new javax.swing.JTextField();
        pay_cash_btn = new javax.swing.JButton();
        cheque_pay_btn = new javax.swing.JButton();
        cheque_panel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cheque_date_choose = new com.toedter.calendar.JDateChooser();
        payer_name_text = new javax.swing.JTextField();
        bank_name_text = new javax.swing.JTextField();
        amount_cheque_label = new javax.swing.JLabel();
        branch_name_text = new javax.swing.JTextField();
        back_cheque_btn = new javax.swing.JButton();
        pay_cheque_btn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cheque_no_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Pay Now");

        jLabel2.setText("Name :");

        jLabel3.setText("Surname :");

        jLabel4.setText("Amount Paid :");

        jLabel5.setText("Amount Balance :");

        jLabel6.setText("Next Payment By:");

        cash_btn.setText("Pay Now");
        cash_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout main_panelLayout = new org.jdesktop.layout.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, main_panelLayout.createSequentialGroup()
                .add(67, 67, 67)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel3))
                .add(18, 18, 18)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(surname_label)
                    .add(name_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 127, Short.MAX_VALUE)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jLabel5)
                    .add(jLabel4))
                .add(42, 42, 42)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(amt_paid_label)
                    .add(amt_bal_label)
                    .add(payable_label))
                .add(66, 66, 66))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, main_panelLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cash_btn)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(259, 259, 259))
        );

        main_panelLayout.linkSize(new java.awt.Component[] {amt_bal_label, amt_paid_label, name_label, payable_label, surname_label}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panelLayout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(amt_paid_label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, main_panelLayout.createSequentialGroup()
                        .add(name_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 45, Short.MAX_VALUE)
                        .add(surname_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(168, 168, 168))
                    .add(main_panelLayout.createSequentialGroup()
                        .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(main_panelLayout.createSequentialGroup()
                                .add(38, 38, 38)
                                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel5)
                                    .add(amt_bal_label))
                                .add(46, 46, 46)
                                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel6)
                                    .add(payable_label)))
                            .add(main_panelLayout.createSequentialGroup()
                                .add(jLabel2)
                                .add(44, 44, 44)
                                .add(jLabel3)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cash_btn)
                        .add(38, 38, 38))))
        );

        cash_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Payment Gateway");

        jLabel8.setText("Name : ");

        jLabel9.setText("Payment Received :");

        jLabel10.setText("Installment Due :");

        jLabel11.setText("Due Date :");

        jLabel12.setText("Late Fees :");

        jLabel13.setText("Total Payable :");

        cancel_cash_btn.setText("Cancel");
        cancel_cash_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_cash_btnActionPerformed(evt);
            }
        });

        payment_cash_label.setText("Payment :");

        pay_cash_btn.setText("Cash Payment");
        pay_cash_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_cash_btnActionPerformed(evt);
            }
        });

        cheque_pay_btn.setText("Cheque Payment");
        cheque_pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheque_pay_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout cash_panelLayout = new org.jdesktop.layout.GroupLayout(cash_panel);
        cash_panel.setLayout(cash_panelLayout);
        cash_panelLayout.setHorizontalGroup(
            cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, cash_panelLayout.createSequentialGroup()
                .add(46, 46, 46)
                .add(cancel_cash_btn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel7)
                .add(237, 237, 237))
            .add(cash_panelLayout.createSequentialGroup()
                .add(68, 68, 68)
                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cash_panelLayout.createSequentialGroup()
                        .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(jLabel10))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel11)
                        .add(41, 41, 41)
                        .add(due_date_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(61, 61, 61))
                    .add(cash_panelLayout.createSequentialGroup()
                        .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(payment_cash_label)
                            .add(cash_panelLayout.createSequentialGroup()
                                .add(jLabel13)
                                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(cash_panelLayout.createSequentialGroup()
                                        .add(41, 41, 41)
                                        .add(pay_cash_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(77, 77, 77)
                                        .add(pay_cash_btn)
                                        .add(26, 26, 26)
                                        .add(cheque_pay_btn))
                                    .add(cash_panelLayout.createSequentialGroup()
                                        .add(57, 57, 57)
                                        .add(total_payable_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(cash_panelLayout.createSequentialGroup()
                                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel8)
                                    .add(jLabel12))
                                .add(82, 82, 82)
                                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(late_fees_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(pay_recd_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(cash_panelLayout.createSequentialGroup()
                                        .add(name_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(surname_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(installment_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        cash_panelLayout.setVerticalGroup(
            cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cash_panelLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(cancel_cash_btn))
                .add(18, 18, 18)
                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(surname_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel8)
                        .add(name_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(30, 30, 30)
                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(pay_recd_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cash_panelLayout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(installment_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(cash_panelLayout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(due_date_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(41, 41, 41)
                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(late_fees_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(32, 32, 32)
                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(total_payable_cash_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 22, Short.MAX_VALUE)
                .add(cash_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(payment_cash_label)
                    .add(pay_cash_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pay_cash_btn)
                    .add(cheque_pay_btn))
                .add(33, 33, 33))
        );

        cheque_panel.setBackground(new java.awt.Color(255, 255, 255));
        cheque_panel.setPreferredSize(new java.awt.Dimension(713, 375));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText("Cheque Details");

        jLabel15.setText("Payer's Name :");

        jLabel16.setText("Bank Name :");

        jLabel17.setText("Branch Name :");

        jLabel18.setText("Amount :");

        jLabel19.setText("Date on Cheque :");

        back_cheque_btn.setText("Back");
        back_cheque_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_cheque_btnActionPerformed(evt);
            }
        });

        pay_cheque_btn.setText("Make Payment");
        pay_cheque_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_cheque_btnActionPerformed(evt);
            }
        });

        jLabel20.setText("Cheque Number :");

        org.jdesktop.layout.GroupLayout cheque_panelLayout = new org.jdesktop.layout.GroupLayout(cheque_panel);
        cheque_panel.setLayout(cheque_panelLayout);
        cheque_panelLayout.setHorizontalGroup(
            cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, cheque_panelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(236, 236, 236))
            .add(cheque_panelLayout.createSequentialGroup()
                .add(82, 82, 82)
                .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cheque_panelLayout.createSequentialGroup()
                        .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel15)
                            .add(jLabel16)
                            .add(jLabel18))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(bank_name_text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .add(payer_name_text)
                            .add(amount_cheque_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(back_cheque_btn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 67, Short.MAX_VALUE)
                .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pay_cheque_btn)
                    .add(cheque_panelLayout.createSequentialGroup()
                        .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel19)
                            .add(jLabel17)
                            .add(jLabel20))
                        .add(33, 33, 33)
                        .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(cheque_date_choose, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(branch_name_text)
                            .add(cheque_no_text))))
                .add(82, 82, 82))
        );
        cheque_panelLayout.setVerticalGroup(
            cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cheque_panelLayout.createSequentialGroup()
                .add(25, 25, 25)
                .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cheque_panelLayout.createSequentialGroup()
                        .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(36, 36, 36)
                        .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel15)
                            .add(payer_name_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel20)
                            .add(cheque_no_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(21, 21, 21)
                        .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cheque_panelLayout.createSequentialGroup()
                                .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel16)
                                    .add(bank_name_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(28, 28, 28)
                                .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel18)
                                    .add(amount_cheque_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cheque_panelLayout.createSequentialGroup()
                                .add(jLabel17)
                                .add(34, 34, 34)
                                .add(jLabel19))))
                    .add(cheque_panelLayout.createSequentialGroup()
                        .add(branch_name_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(cheque_date_choose, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 72, Short.MAX_VALUE)
                .add(cheque_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(back_cheque_btn)
                    .add(pay_cheque_btn))
                .add(64, 64, 64))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(cash_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(cheque_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(cash_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(cheque_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cash_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_btnActionPerformed
        // TODO add your handling code here:
        main_panel.setVisible(false);
        cash_panel.setVisible(true);
        
    }//GEN-LAST:event_cash_btnActionPerformed

    private void cancel_cash_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_cash_btnActionPerformed
        // TODO add your handling code here:
        cash_panel.setVisible(false);
        main_panel.setVisible(true);
    }//GEN-LAST:event_cancel_cash_btnActionPerformed

    private void pay_cash_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_cash_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            if(JOptionPane.showConfirmDialog(null, "Pay Rs."+pay_cash_text.getText()+" ?","Confirmation", JOptionPane.OK_CANCEL_OPTION) == 0)
            {
        int type=rs.getInt("type_of_pay");
        java.util.Date d1= new Date();
        java.text.DateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String reportDate1 = df.format(d1);
        java.util.Calendar c = java.util.Calendar.getInstance(); 
        c.setTime(d1); 
        if(type==1)
            {
                
                c.add(java.util.Calendar.MONTH, 1);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
            }
            else if(type==2)
            {
                c.add(java.util.Calendar.MONTH, 3);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
            }
            else if(type==3)
            {
                c.add(java.util.Calendar.MONTH, 6);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
            }
            else if(type==4)
            {
                c.add(java.util.Calendar.MONTH, 12);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
            }
        double payed = Double.parseDouble(pay_cash_text.getText());
        payed-=this.late;
        double temp = rs.getDouble("pay_recd");
        payed+=temp;
        rs.updateDouble("pay_recd", payed);
        temp=rs.getDouble("pay_bal");
        temp-=payed;
        if(temp<=0)
        {
            temp=0;
        }
        rs.updateDouble("pay_bal", temp);
        int n = rs.getInt("no_of_pays_made");
        n++;
        rs.updateInt("no_of_pays_made", n);
        rs.updateRow();
        String sql="select * from cash_transact";
        rs1=stmt1.executeQuery(sql);
        rs1.moveToInsertRow();
        rs1.updateInt("student_id", rs.getInt("id"));
        rs1.updateString("date_of_pay",reportDate1);
        rs1.updateDouble("amount",Double.parseDouble(pay_cash_text.getText()));
        rs1.insertRow();
        rs1.close();
        stmt1.close();
        stmt1=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        rs1=stmt1.executeQuery(sql);
        JOptionPane.showMessageDialog(null, "Paid Rs."+pay_cash_text.getText(), "Congratulations", 1);
        this.dispose();
        new OldStudent().setVisible(true);
        }
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
    }//GEN-LAST:event_pay_cash_btnActionPerformed

    private void cheque_pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheque_pay_btnActionPerformed
        // TODO add your handling code here:
        cash_panel.setVisible(false);
        cheque_panel.setVisible(true);
        amount_cheque_label.setText(pay_cash_text.getText());
    }//GEN-LAST:event_cheque_pay_btnActionPerformed

    private void back_cheque_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_cheque_btnActionPerformed
        // TODO add your handling code here:
        cheque_panel.setVisible(false);
        cash_panel.setVisible(true);
    }//GEN-LAST:event_back_cheque_btnActionPerformed

    private void pay_cheque_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_cheque_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            if(JOptionPane.showConfirmDialog(null, "Pay Rs."+pay_cash_text.getText()+" ?","Confirmation", JOptionPane.OK_CANCEL_OPTION) == 0)
            {
        int type=rs.getInt("type_of_pay");
        java.util.Date d1= new Date();
        java.text.DateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String reportDate1 = df.format(d1);
        java.util.Calendar c = java.util.Calendar.getInstance(); 
        c.setTime(d1); 
        if(type==1)
            {
                
                c.add(java.util.Calendar.MONTH, 1);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
            }
            else if(type==2)
            {
                c.add(java.util.Calendar.MONTH, 3);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
            }
            else if(type==3)
            {
                c.add(java.util.Calendar.MONTH, 6);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
            }
            else if(type==4)
            {
                c.add(java.util.Calendar.MONTH, 12);
                java.util.Date d2= c.getTime();
                String reportDate2=df.format(d2);
                rs.updateString("date_to_pay_by", reportDate2);
            }
        double payed = Double.parseDouble(pay_cash_text.getText());
        payed-=this.late;
        double temp = rs.getDouble("pay_recd");
        payed+=temp;
        rs.updateDouble("pay_recd", payed);
        temp=rs.getDouble("pay_bal");
        temp-=payed;
        if(temp<=0)
        {
            temp=0;
        }
        rs.updateDouble("pay_bal", temp);
        int n = rs.getInt("no_of_pays_made");
        n++;
        rs.updateInt("no_of_pays_made", n);
        rs.updateRow();
        cash_panel.setVisible(false);
        cheque_panel.setVisible(true);
        String sql="select * from cheque_transact";
        rs1=stmt1.executeQuery(sql);
        rs1.moveToInsertRow();
        rs1.updateInt("student_id", rs.getInt("id"));
        rs1.updateLong("cheque_no",Long.parseLong(cheque_no_text.getText()));
        rs1.updateString("payer_name", payer_name_text.getText());
        rs1.updateString("bank_name", bank_name_text.getText());
        rs1.updateString("branch", branch_name_text.getText());
        Date dc=cheque_date_choose.getDate();
        String chequeDate = df.format(dc);
        rs1.updateString("date_on_cheque", chequeDate);
        rs1.updateString("date_of_pay",reportDate1);
        rs1.updateDouble("amount",Double.parseDouble(pay_cash_text.getText()));
        rs1.insertRow();
        rs1.close();
        stmt1.close();
        stmt1=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        rs1=stmt1.executeQuery(sql);
        JOptionPane.showMessageDialog(null, "Paid Rs."+pay_cash_text.getText(), "Congratulations", 1);
        this.dispose();
        new OldStudent().setVisible(true);
        }
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
    }//GEN-LAST:event_pay_cheque_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pay_now.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pay_now.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pay_now.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pay_now.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount_cheque_label;
    private javax.swing.JLabel amt_bal_label;
    private javax.swing.JLabel amt_paid_label;
    private javax.swing.JButton back_cheque_btn;
    private javax.swing.JTextField bank_name_text;
    private javax.swing.JTextField branch_name_text;
    private javax.swing.JButton cancel_cash_btn;
    private javax.swing.JButton cash_btn;
    private javax.swing.JPanel cash_panel;
    private com.toedter.calendar.JDateChooser cheque_date_choose;
    private javax.swing.JTextField cheque_no_text;
    private javax.swing.JPanel cheque_panel;
    private javax.swing.JButton cheque_pay_btn;
    private javax.swing.JLabel due_date_cash_label;
    private javax.swing.JLabel installment_cash_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel late_fees_cash_label;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel name_cash_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JButton pay_cash_btn;
    private javax.swing.JTextField pay_cash_text;
    private javax.swing.JButton pay_cheque_btn;
    private javax.swing.JLabel pay_recd_label;
    private javax.swing.JLabel payable_label;
    private javax.swing.JTextField payer_name_text;
    private javax.swing.JLabel payment_cash_label;
    private javax.swing.JLabel surname_cash_label;
    private javax.swing.JLabel surname_label;
    private javax.swing.JLabel total_payable_cash_label;
    // End of variables declaration//GEN-END:variables
}
