
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Arrays;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vivektejwani
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public static double late_amt;
    public static String username="",pass="";
    Connection con;
    Statement stmt;
    ResultSet rs;
    int id;
    public StartPage() {
        initComponents();
        invalid_label.setVisible(false);
        new_btn.setVisible(false);
        old_btn.setVisible(false);
        users_btn.setVisible(false);
        new_courses_btn.setVisible(false);
        old_courses_btn.setVisible(false);
        settings_btn.setVisible(false);
        settings_panel.setVisible(false);
        doConnect();
    }
    public void doConnect()
    {
        
            if(username=="" && pass=="")
            {
                username = JOptionPane.showInputDialog("Database Server Username :");
                pass = JOptionPane.showInputDialog("Database Server Password :");
            }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start_panel = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        user_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        user_text = new javax.swing.JTextField();
        pass_text = new javax.swing.JPasswordField();
        submit_btn = new javax.swing.JButton();
        invalid_label = new javax.swing.JLabel();
        new_btn = new javax.swing.JButton();
        old_btn = new javax.swing.JButton();
        new_courses_btn = new javax.swing.JButton();
        users_btn = new javax.swing.JButton();
        old_courses_btn = new javax.swing.JButton();
        settings_btn = new javax.swing.JButton();
        setup_btn = new javax.swing.JButton();
        settings_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        late_penalty_text = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        start_panel.setBackground(new java.awt.Color(255, 255, 255));

        welcome_label.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        welcome_label.setText("Welcome to the Student Accounting System!");

        user_label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        user_label.setText("Username :");

        pass_label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pass_label.setText("Password :");

        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        invalid_label.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        invalid_label.setText("Invalid !");

        new_btn.setText("New Student");
        new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btnActionPerformed(evt);
            }
        });

        old_btn.setText("Old Student");
        old_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                old_btnActionPerformed(evt);
            }
        });

        new_courses_btn.setText("New Courses");
        new_courses_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_courses_btnActionPerformed(evt);
            }
        });

        users_btn.setText("Users");
        users_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                users_btnActionPerformed(evt);
            }
        });

        old_courses_btn.setText("Old Courses");
        old_courses_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                old_courses_btnActionPerformed(evt);
            }
        });

        settings_btn.setText("Settings");
        settings_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settings_btnActionPerformed(evt);
            }
        });

        setup_btn.setText("Setup Database");
        setup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setup_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout start_panelLayout = new org.jdesktop.layout.GroupLayout(start_panel);
        start_panel.setLayout(start_panelLayout);
        start_panelLayout.setHorizontalGroup(
            start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(start_panelLayout.createSequentialGroup()
                .add(290, 290, 290)
                .add(logo)
                .add(0, 513, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, start_panelLayout.createSequentialGroup()
                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(start_panelLayout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(welcome_label)
                            .add(start_panelLayout.createSequentialGroup()
                                .add(settings_btn)
                                .add(206, 206, 206)
                                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(new_btn)
                                    .add(start_panelLayout.createSequentialGroup()
                                        .add(submit_btn)
                                        .add(94, 94, 94)
                                        .add(invalid_label)))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(setup_btn))
                    .add(start_panelLayout.createSequentialGroup()
                        .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(start_panelLayout.createSequentialGroup()
                                .add(262, 262, 262)
                                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(user_label)
                                    .add(pass_label)))
                            .add(start_panelLayout.createSequentialGroup()
                                .add(24, 24, 24)
                                .add(new_courses_btn)
                                .add(29, 29, 29)
                                .add(old_courses_btn)))
                        .add(74, 74, 74)
                        .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(start_panelLayout.createSequentialGroup()
                                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(user_text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .add(pass_text))
                                .add(0, 0, Short.MAX_VALUE))
                            .add(start_panelLayout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(old_btn)
                                .add(65, 65, 65)
                                .add(users_btn)))))
                .add(27, 27, 27))
        );
        start_panelLayout.setVerticalGroup(
            start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(start_panelLayout.createSequentialGroup()
                .add(25, 25, 25)
                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(welcome_label)
                    .add(setup_btn))
                .add(18, 18, 18)
                .add(logo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(user_label)
                    .add(user_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pass_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pass_label))
                .add(60, 60, 60)
                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(submit_btn)
                        .add(settings_btn))
                    .add(invalid_label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                .add(start_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(new_btn)
                    .add(old_btn)
                    .add(new_courses_btn)
                    .add(users_btn)
                    .add(old_courses_btn))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        settings_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Settings");

        jLabel2.setText("Late Penalty (Per day) :");

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout settings_panelLayout = new org.jdesktop.layout.GroupLayout(settings_panel);
        settings_panel.setLayout(settings_panelLayout);
        settings_panelLayout.setHorizontalGroup(
            settings_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settings_panelLayout.createSequentialGroup()
                .add(settings_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(settings_panelLayout.createSequentialGroup()
                        .add(366, 366, 366)
                        .add(jLabel1))
                    .add(settings_panelLayout.createSequentialGroup()
                        .add(80, 80, 80)
                        .add(jLabel2)
                        .add(42, 42, 42)
                        .add(late_penalty_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(settings_panelLayout.createSequentialGroup()
                        .add(188, 188, 188)
                        .add(back_btn)
                        .add(183, 183, 183)
                        .add(save_btn)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        settings_panelLayout.setVerticalGroup(
            settings_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settings_panelLayout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jLabel1)
                .add(44, 44, 44)
                .add(settings_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(late_penalty_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 152, Short.MAX_VALUE)
                .add(settings_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(back_btn)
                    .add(save_btn))
                .add(56, 56, 56))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(start_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(settings_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(start_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(settings_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College?zeroDateTimeBehavior=convertToNull", username, pass);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String user=user_text.getText();
            char[] pass=pass_text.getPassword();
            String sql = "select * from users where username = '"+user+"'";
            rs=stmt.executeQuery(sql);
            if(rs.next())
            {   
                this.id= rs.getInt("id");
                char[] correct=rs.getString("password").toCharArray();
                if(Arrays.equals(pass, correct))
                {
                    invalid_label.setVisible(false);
                    new_btn.setVisible(true);
                    old_btn.setVisible(true);
                    users_btn.setVisible(true);
                    new_courses_btn.setVisible(true);
                    new_courses_btn.setEnabled(false);
                    old_courses_btn.setVisible(true);
                    old_courses_btn.setEnabled(false);
                    settings_btn.setVisible(true);
                    settings_btn.setEnabled(false);
                    sql = "select * from users where username = '"+user+"'";
                    rs=stmt.executeQuery(sql);
                    rs.next();
                    late_amt=rs.getDouble("late_amt");
                    if(user.equalsIgnoreCase("admin"))
                    {
                        new_courses_btn.setEnabled(true);
                        old_courses_btn.setEnabled(true);
                        settings_btn.setEnabled(true);
                    }
                 
                }
                else
                {
                    invalid_label.setVisible(true);
                    new_btn.setVisible(false);
                    old_btn.setVisible(false);
                    users_btn.setVisible(false);
                    new_courses_btn.setVisible(false);
                    old_courses_btn.setVisible(false);
                    settings_btn.setVisible(false);
                }
            }
            else
            {
                     invalid_label.setVisible(true);
                     new_btn.setVisible(false);
                     old_btn.setVisible(false);
                    users_btn.setVisible(false);
                    new_courses_btn.setVisible(false);
                    old_courses_btn.setVisible(false);
                    settings_btn.setVisible(false);
            }
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        new NewStudent().setVisible(true);
    }//GEN-LAST:event_new_btnActionPerformed

    private void old_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_old_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        new OldStudent().setVisible(true);
    }//GEN-LAST:event_old_btnActionPerformed

    private void users_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_users_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Users(id).setVisible(true);
    }//GEN-LAST:event_users_btnActionPerformed

    private void new_courses_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_courses_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new NewCourses().setVisible(true);
    }//GEN-LAST:event_new_courses_btnActionPerformed

    private void old_courses_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_old_courses_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new OldCourses().setVisible(true);
    }//GEN-LAST:event_old_courses_btnActionPerformed

    private void settings_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settings_btnActionPerformed
        // TODO add your handling code here:
        start_panel.setVisible(false);
        settings_panel.setVisible(true);
        late_penalty_text.setText(Double.toString(this.late_amt));
    }//GEN-LAST:event_settings_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        settings_panel.setVisible(false);
        start_panel.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        try
        {    
            this.late_amt=Double.parseDouble(late_penalty_text.getText());
            String sql="select * from users";
            rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                rs.updateDouble("late_amt", late_amt);
                rs.updateRow();
            }
            JOptionPane.showMessageDialog(null, "Saved", null, 1);
            settings_panel.setVisible(false);
            start_panel.setVisible(true);
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null,err.getMessage(),"Error", 1);
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void setup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setup_btnActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Is this the first time you are using this software on your computer?", "Confirmation!", JOptionPane.OK_CANCEL_OPTION) == 0)
        {
            try
            {
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306",username,pass);
                stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String start="create database College";
                stmt.execute(start);
                start="use College";
                stmt.execute(start);
                start="CREATE TABLE IF NOT EXISTS cash_transact (" +
                "  id int(11) NOT NULL AUTO_INCREMENT," +
                "  student_id int(11) NOT NULL," +
                "  date_of_pay text NOT NULL," +
                "  amount double NOT NULL," +
                "  PRIMARY KEY (id)" +
                ")";
                stmt.execute(start);
                start="CREATE TABLE IF NOT EXISTS cheque_transact (" +
                "  id int(11) NOT NULL AUTO_INCREMENT," +
                "  student_id int(11) NOT NULL," +
                "  cheque_no bigint(20) NOT NULL," +
                "  payer_name text NOT NULL," +
                "  bank_name text NOT NULL," +
                "  branch text NOT NULL," +
                "  amount double NOT NULL," +
                "  date_of_pay text NOT NULL," +
                "  date_on_cheque text NOT NULL," +
                "  PRIMARY KEY (id)" +
                ")";
                stmt.execute(start);
                start="CREATE TABLE IF NOT EXISTS courses (" +
                "  course_name text NOT NULL," +
                "  duration int(11) NOT NULL," +
                "  fees double NOT NULL," +
                "  education_cess double NOT NULL," +
                "  other_tax double NOT NULL," +
                "  id int(11) NOT NULL AUTO_INCREMENT," +
                "  PRIMARY KEY (id)" +
                ")";
                stmt.execute(start);
                start="CREATE TABLE IF NOT EXISTS student_details (" +
                "  id int(11) NOT NULL AUTO_INCREMENT," +
                "  stud_name text NOT NULL," +
                "  surname text NOT NULL," +
                "  roll_no int(11) NOT NULL," +
                "  reg_no text NOT NULL," +
                "  father_name text NOT NULL," +
                "  mother_name text NOT NULL," +
                "  address text NOT NULL," +
                "  dob text NOT NULL," +
                "  school text NOT NULL," +
                "  board text NOT NULL," +
                "  contact_no bigint(11) NOT NULL," +
                "  parent_contact bigint(20) NOT NULL," +
                "  stud_email text NOT NULL," +
                "  parent_email text NOT NULL," +
                "  course_name text NOT NULL," +
                "  joining_date text NOT NULL," +
                "  father_occupation text NOT NULL," +
                "  mother_occupation text NOT NULL," +
                "  fees double NOT NULL," +
                "  date_to_pay_by text NOT NULL," +
                "  percentage int(11) NOT NULL," +
                "  pay_recd double NOT NULL," +
                "  pay_bal double NOT NULL," +
                "  type_of_pay int(11) NOT NULL," +
                "  no_of_pays_made int(11) NOT NULL," +
                "  install_amt double NOT NULL," +
                "  PRIMARY KEY (id)," +
                "  KEY id (id)," +
                "  KEY id_2 (id)" +
                ")";
                stmt.execute(start);
                start="CREATE TABLE IF NOT EXISTS users (" +
                "  id int(11) NOT NULL AUTO_INCREMENT," +
                "  username text NOT NULL," +
                "  password text NOT NULL," +
                "  late_amt double NOT NULL," +        
                "  PRIMARY KEY (id)" +
                ") ";
                stmt.execute(start);
                start="select * from users";
                rs=stmt.executeQuery(start);
                rs.moveToInsertRow();
                rs.updateString("username", "admin");
                rs.updateString("password", "admin");
                rs.updateInt("id", 0);
                rs.updateDouble("late_amt", 0.5);
                rs.insertRow();
                rs.close();
                stmt.close();
                user_text.setText("admin");
                pass_text.setText("admin");
                
            }
            catch(SQLException err)
            {
                JOptionPane.showMessageDialog(null,err.getMessage(),"Error", 1);
            }
        }
    }//GEN-LAST:event_setup_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel invalid_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField late_penalty_text;
    private javax.swing.JLabel logo;
    private javax.swing.JButton new_btn;
    private javax.swing.JButton new_courses_btn;
    private javax.swing.JButton old_btn;
    private javax.swing.JButton old_courses_btn;
    private javax.swing.JLabel pass_label;
    private javax.swing.JPasswordField pass_text;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton settings_btn;
    private javax.swing.JPanel settings_panel;
    private javax.swing.JButton setup_btn;
    private javax.swing.JPanel start_panel;
    private javax.swing.JButton submit_btn;
    private javax.swing.JLabel user_label;
    private javax.swing.JTextField user_text;
    private javax.swing.JButton users_btn;
    private javax.swing.JLabel welcome_label;
    // End of variables declaration//GEN-END:variables
}
