/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Arrays;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author vivektejwani
 */
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form Users
     */
    Connection con;
    Statement stmt;
    ResultSet rs;
    int id,del_id;
    boolean admin;
    String user,sql,pass,del_name;
    public Users() {
        initComponents();
    }
    public Users(int uid)
    {
        initComponents();
        id=uid;
        main_panel.setVisible(true);
        change_panel.setVisible(false);
        delete_panel.setVisible(false);
        add_panel.setVisible(false);
        doConnect();
        
    }
    public void doConnect()
    {
        try
        {
            add_btn.setEnabled(false);
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College?zeroDateTimeBehavior=convertToNull", StartPage.username,StartPage.pass);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            sql = "select * from users where id = "+id;
            rs=stmt.executeQuery(sql);
            rs.next();
            username_label.setText(rs.getString("username"));
            user_stored_label.setText(rs.getString("username"));
            user=rs.getString("username");
            admin=rs.getString("username").equalsIgnoreCase("admin");
            pass=rs.getString("password");
            if(admin)
            {
                add_btn.setEnabled(true);
            }
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delete_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        user_find_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        find_btn = new javax.swing.JButton();
        delete_user_btn = new javax.swing.JButton();
        back_delete_btn = new javax.swing.JButton();
        change_panel = new javax.swing.JPanel();
        back_change_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        user_stored_label = new javax.swing.JLabel();
        new_pass1_text = new javax.swing.JTextField();
        new_pass2_text = new javax.swing.JTextField();
        old_pass_text = new javax.swing.JPasswordField();
        update_pass_btn = new javax.swing.JButton();
        add_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        new_user_text = new javax.swing.JTextField();
        new_pass_text = new javax.swing.JTextField();
        add_final_btn = new javax.swing.JButton();
        back_add_btn = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        change_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        delete_panel.setBackground(new java.awt.Color(255, 255, 255));

        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        user_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(user_table);

        jLabel8.setText("Username :");

        find_btn.setText("Find");
        find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_btnActionPerformed(evt);
            }
        });

        delete_user_btn.setText("Delete");
        delete_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_user_btnActionPerformed(evt);
            }
        });

        back_delete_btn.setText("Back");
        back_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_delete_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout delete_panelLayout = new org.jdesktop.layout.GroupLayout(delete_panel);
        delete_panel.setLayout(delete_panelLayout);
        delete_panelLayout.setHorizontalGroup(
            delete_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, delete_panelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel8)
                .add(82, 82, 82)
                .add(user_find_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(203, 203, 203))
            .add(delete_panelLayout.createSequentialGroup()
                .add(delete_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(delete_panelLayout.createSequentialGroup()
                        .add(129, 129, 129)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(delete_panelLayout.createSequentialGroup()
                        .add(249, 249, 249)
                        .add(find_btn)
                        .add(58, 58, 58)
                        .add(delete_user_btn))
                    .add(delete_panelLayout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(back_delete_btn)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        delete_panelLayout.setVerticalGroup(
            delete_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(delete_panelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(back_delete_btn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(39, 39, 39)
                .add(delete_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(user_find_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .add(49, 49, 49)
                .add(delete_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(find_btn)
                    .add(delete_user_btn))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        change_panel.setBackground(new java.awt.Color(255, 255, 255));

        back_change_btn.setText("Back");
        back_change_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_change_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Username :");

        jLabel5.setText("Old Password :");

        jLabel6.setText("New Password :");

        jLabel7.setText("Confirm Password :");

        update_pass_btn.setText("Update");
        update_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_pass_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout change_panelLayout = new org.jdesktop.layout.GroupLayout(change_panel);
        change_panel.setLayout(change_panelLayout);
        change_panelLayout.setHorizontalGroup(
            change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(change_panelLayout.createSequentialGroup()
                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(change_panelLayout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(back_change_btn))
                    .add(change_panelLayout.createSequentialGroup()
                        .add(195, 195, 195)
                        .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(change_panelLayout.createSequentialGroup()
                                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6)
                                    .add(jLabel7))
                                .add(87, 87, 87)
                                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(new_pass1_text)
                                    .add(new_pass2_text)))
                            .add(change_panelLayout.createSequentialGroup()
                                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel4)
                                    .add(jLabel5))
                                .add(116, 116, 116)
                                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(user_stored_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(old_pass_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(change_panelLayout.createSequentialGroup()
                        .add(306, 306, 306)
                        .add(update_pass_btn)))
                .add(178, 178, 178))
        );
        change_panelLayout.setVerticalGroup(
            change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(change_panelLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(back_change_btn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(user_stored_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(40, 40, 40)
                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(old_pass_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(32, 32, 32)
                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(new_pass1_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(change_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(new_pass2_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 37, Short.MAX_VALUE)
                .add(update_pass_btn)
                .add(30, 30, 30))
        );

        add_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("New Username :");

        jLabel3.setText("New Password :");

        new_user_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_user_textActionPerformed(evt);
            }
        });

        add_final_btn.setText("Add");
        add_final_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_final_btnActionPerformed(evt);
            }
        });

        back_add_btn.setText("Back");
        back_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_add_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout add_panelLayout = new org.jdesktop.layout.GroupLayout(add_panel);
        add_panel.setLayout(add_panelLayout);
        add_panelLayout.setHorizontalGroup(
            add_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(add_panelLayout.createSequentialGroup()
                .add(add_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(add_panelLayout.createSequentialGroup()
                        .add(172, 172, 172)
                        .add(add_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .add(30, 30, 30)
                        .add(add_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(new_user_text)
                            .add(new_pass_text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .add(add_panelLayout.createSequentialGroup()
                        .add(299, 299, 299)
                        .add(add_final_btn))
                    .add(add_panelLayout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(back_add_btn)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        add_panelLayout.setVerticalGroup(
            add_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(add_panelLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(back_add_btn)
                .add(45, 45, 45)
                .add(add_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(new_user_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(50, 50, 50)
                .add(add_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(new_pass_text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 69, Short.MAX_VALUE)
                .add(add_final_btn)
                .add(63, 63, 63))
        );

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("You have logged in as :");

        username_label.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        add_btn.setText("Add User");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        change_btn.setText("Change Settings");
        change_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("Delete User");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout main_panelLayout = new org.jdesktop.layout.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panelLayout.createSequentialGroup()
                .add(80, 80, 80)
                .add(add_btn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 101, Short.MAX_VALUE)
                .add(change_btn)
                .add(101, 101, 101)
                .add(delete_btn)
                .add(76, 76, 76))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, main_panelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1)
                .add(77, 77, 77)
                .add(username_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(100, 100, 100))
            .add(main_panelLayout.createSequentialGroup()
                .add(41, 41, 41)
                .add(logout_btn)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panelLayout.createSequentialGroup()
                .add(21, 21, 21)
                .add(logout_btn)
                .add(18, 18, 18)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(username_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 137, Short.MAX_VALUE)
                .add(main_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(add_btn)
                    .add(change_btn)
                    .add(delete_btn))
                .add(109, 109, 109))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(add_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(change_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(delete_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(add_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(change_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(delete_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        main_panel.setVisible(false);
        add_panel.setVisible(true);
    }//GEN-LAST:event_add_btnActionPerformed

    private void change_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_btnActionPerformed
        // TODO add your handling code here:
        main_panel.setVisible(false);
        change_panel.setVisible(true);
    }//GEN-LAST:event_change_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        if(admin)
        {
            
            delete_user_btn.setEnabled(false);
            delete_panel.setVisible(true);
            main_panel.setVisible(false);
        }
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Delete "+user+" ?", "Confirmation!", JOptionPane.OK_CANCEL_OPTION) == 0)
            {
                try
                {
                    rs.deleteRow();
                    stmt.close();
                    rs.close();
                    JOptionPane.showMessageDialog(null,"Deleted!",null,1);
                    this.dispose();
                    new StartPage().setVisible(true);
                }
                catch(SQLException err)
                {
                    JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
                }  
            }
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void new_user_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_user_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_user_textActionPerformed

    private void add_final_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_final_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            if(new_user_text.getText().equalsIgnoreCase("admin"))
            {
                JOptionPane.showMessageDialog(null, "Cannot add another admin!", "Warning", 1);
            }
            else
            {
            while(rs.next())
            {}
            rs.previous();
            rs.moveToInsertRow();
            rs.updateString("username",new_user_text.getText());
            rs.updateString("password", new_pass_text.getText());
            rs.updateDouble("late_amt", StartPage.late_amt);
            rs.insertRow();
            stmt.close();
            rs.close();
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs=stmt.executeQuery(sql);
            rs.next();
            JOptionPane.showMessageDialog(null, "User Added!", "Alert", 1);
            add_panel.setVisible(false);
            main_panel.setVisible(true);
            }
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
        
    }//GEN-LAST:event_add_final_btnActionPerformed

    private void back_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_add_btnActionPerformed
        // TODO add your handling code here:
        add_panel.setVisible(false);
        main_panel.setVisible(true);
    }//GEN-LAST:event_back_add_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new StartPage().setVisible(true);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void back_change_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_change_btnActionPerformed
        // TODO add your handling code here:
        change_panel.setVisible(false);
        main_panel.setVisible(true);
    }//GEN-LAST:event_back_change_btnActionPerformed

    private void update_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_pass_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            
            char[] old=old_pass_text.getPassword();
            char[] correct=pass.toCharArray();
            if(Arrays.equals(old, correct))
            {
                if(new_pass1_text.getText().equals(new_pass2_text.getText()))
                {
                    rs.updateString("password", new_pass1_text.getText());
                    rs.updateRow();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "The two new passwords must be the same.", "Error", 1);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please type the correct old password.", "Error", 1);
                
            }
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
    }//GEN-LAST:event_update_pass_btnActionPerformed

    private void find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql1 = "select id,username from users where username = '"+user_find_text.getText()+"'";
            rs=stmt.executeQuery(sql1);
            user_table.setModel(DbUtils.resultSetToTableModel(rs));
            TableColumnModel cm = user_table.getColumnModel();
            cm.removeColumn(cm.getColumn(2));
            
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
        }
    }//GEN-LAST:event_find_btnActionPerformed

    private void user_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tableMouseClicked
        // TODO add your handling code here:
        int row = user_table.rowAtPoint(evt.getPoint());
        user_table.setRowSelectionInterval(row, row);
        del_name = (String)user_table.getModel().getValueAt(row, 1);
        del_id = (Integer)user_table.getModel().getValueAt(row, 0);
        delete_user_btn.setEnabled(true);
    }//GEN-LAST:event_user_tableMouseClicked

    private void delete_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_user_btnActionPerformed
        // TODO add your handling code here:
        if(del_name.equalsIgnoreCase("admin"))
        {
            JOptionPane.showMessageDialog(null,"Admin cannot be deleted!","Warning!",1);
        }
        else    if(JOptionPane.showConfirmDialog(null, "Delete "+del_name+" ?", "Confirmation!", JOptionPane.OK_CANCEL_OPTION) == 0)
            {
                try
                {
                    String sql1="select * from users where username = '"+del_name+"'";
                    rs=stmt.executeQuery(sql1);
                    rs.next();
                    rs.deleteRow();
                    stmt.close();
                    rs.close();
                    JOptionPane.showMessageDialog(null,"Deleted!",null,1);
                    new Users(id).setVisible(true);
                }
                catch(SQLException err)
                {
                    JOptionPane.showMessageDialog(null, err.getMessage(), "Error!", 1);
                }  
            }
    }//GEN-LAST:event_delete_user_btnActionPerformed

    private void back_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_delete_btnActionPerformed
        // TODO add your handling code here:
        delete_panel.setVisible(false);
        main_panel.setVisible(true);
    }//GEN-LAST:event_back_delete_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton add_final_btn;
    private javax.swing.JPanel add_panel;
    private javax.swing.JButton back_add_btn;
    private javax.swing.JButton back_change_btn;
    private javax.swing.JButton back_delete_btn;
    private javax.swing.JButton change_btn;
    private javax.swing.JPanel change_panel;
    private javax.swing.JButton delete_btn;
    private javax.swing.JPanel delete_panel;
    private javax.swing.JButton delete_user_btn;
    private javax.swing.JButton find_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField new_pass1_text;
    private javax.swing.JTextField new_pass2_text;
    private javax.swing.JTextField new_pass_text;
    private javax.swing.JTextField new_user_text;
    private javax.swing.JPasswordField old_pass_text;
    private javax.swing.JButton update_pass_btn;
    private javax.swing.JTextField user_find_text;
    private javax.swing.JLabel user_stored_label;
    private javax.swing.JTable user_table;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
